"""Public wire contracts for the SimplyNext backend."""

from typing import Annotated, TypeAlias

from pydantic import Field

from .common import Confidence, ContractModel, Identifier, SignLanguage
from .events import (
    AckEvent,
    ActivityEvent,
    ActivityState,
    ErrorCode,
    ErrorEvent,
    LatticeAckEvent,
    LatticeChoice,
    LatticeEvidenceTrace,
    LatticeRepairRequiredEvent,
    LatticeResultEvent,
    LatticeTerminalEvent,
    OutboundEvent,
    PongEvent,
    RepairRequiredEvent,
    UtteranceResultEvent,
)
from .landmarks import (
    FACE_LANDMARK_INDICES,
    FACE_LANDMARK_NAMES,
    HAND_LANDMARK_NAMES,
    LANDMARK_SCHEMA_VERSION,
    MAX_CONTRACT_BATCH_FRAMES,
    POSE_LANDMARK_INDICES,
    POSE_LANDMARK_NAMES,
    CameraGeometry,
    FaceLandmarks,
    HandLandmarks,
    LandmarkBatch,
    LandmarkFrame,
    LandmarkLayout,
    LandmarkPoint,
    PoseLandmarks,
)
from .lattices import (
    GLOSS_LATTICE_SCHEMA_VERSION,
    MAX_GLOSS_CANDIDATES_PER_SLOT,
    MAX_GLOSS_LATTICE_BYTES,
    MAX_GLOSS_LATTICE_SLOTS,
    ClassifierDescriptor,
    GlossCandidate,
    GlossLattice,
    GlossLatticeProducer,
    GlossLatticeQuality,
    GlossLatticeSlot,
    GlossProvenance,
)
from .sessions import (
    ClientDescriptor,
    ClientPlatform,
    ControlAction,
    DetectorDelegate,
    DetectorDescriptor,
    SessionCreateRequest,
    SessionCreateResponse,
    SessionRequest,
    SessionResponse,
    StreamControlMessage,
    StreamKind,
)
from .utterances import (
    GlossHypothesis,
    RepairAction,
    TranslationResult,
    TranslationStatus,
    UtterancePayload,
    UtteranceRequest,
    UtteranceResponse,
)

InboundStreamMessage: TypeAlias = Annotated[
    LandmarkBatch | StreamControlMessage,
    Field(discriminator="type"),
]

InboundLatticeStreamMessage: TypeAlias = Annotated[
    GlossLattice | StreamControlMessage,
    Field(discriminator="type"),
]

__all__ = [
    "AckEvent",
    "ActivityEvent",
    "ActivityState",
    "CameraGeometry",
    "ClientDescriptor",
    "ClientPlatform",
    "ClassifierDescriptor",
    "Confidence",
    "ContractModel",
    "ControlAction",
    "DetectorDelegate",
    "DetectorDescriptor",
    "ErrorCode",
    "ErrorEvent",
    "FACE_LANDMARK_INDICES",
    "FACE_LANDMARK_NAMES",
    "FaceLandmarks",
    "GlossHypothesis",
    "GlossCandidate",
    "GlossLattice",
    "GlossLatticeProducer",
    "GlossLatticeQuality",
    "GlossLatticeSlot",
    "GlossProvenance",
    "HAND_LANDMARK_NAMES",
    "HandLandmarks",
    "Identifier",
    "InboundLatticeStreamMessage",
    "InboundStreamMessage",
    "GLOSS_LATTICE_SCHEMA_VERSION",
    "LANDMARK_SCHEMA_VERSION",
    "LandmarkBatch",
    "LandmarkFrame",
    "LandmarkLayout",
    "LandmarkPoint",
    "LatticeAckEvent",
    "LatticeChoice",
    "LatticeEvidenceTrace",
    "LatticeRepairRequiredEvent",
    "LatticeResultEvent",
    "LatticeTerminalEvent",
    "MAX_GLOSS_CANDIDATES_PER_SLOT",
    "MAX_GLOSS_LATTICE_BYTES",
    "MAX_GLOSS_LATTICE_SLOTS",
    "MAX_CONTRACT_BATCH_FRAMES",
    "OutboundEvent",
    "PongEvent",
    "POSE_LANDMARK_INDICES",
    "POSE_LANDMARK_NAMES",
    "PoseLandmarks",
    "RepairAction",
    "RepairRequiredEvent",
    "SessionCreateRequest",
    "SessionCreateResponse",
    "SessionRequest",
    "SessionResponse",
    "SignLanguage",
    "StreamKind",
    "StreamControlMessage",
    "TranslationResult",
    "TranslationStatus",
    "UtterancePayload",
    "UtteranceRequest",
    "UtteranceResponse",
    "UtteranceResultEvent",
]
